# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09ceb8b4303a6f6ea2c0785d8cd14ec38b1343b779dbe94da560f5f2b8b458ed28e8ed8f770651658b28ee38610ffe90631bc43292a3cc2eb9570adab90dd6df

test:
  secret_key_base: 486e07f9da35a8b72581f2d059721e31bf1983ad6e892d717ea0bc97f907b1a0c681d87433ec3c764c902b267bc4cdc1cf69bab4a6e732615c8a5aa917940f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
